"""add patients

Revision ID: 8361f153ca45
Revises: d757d5d4d9bf
Create Date: 2026-07-07 00:22:04.080402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8361f153ca45'
down_revision = 'd757d5d4d9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('medical_file_number', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('search_name', sa.String(length=360), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_years_at_registration', sa.Integer(), nullable=True),
    sa.Column('age_recorded_at', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=False),
    sa.Column('is_virgin', sa.Boolean(), nullable=False),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('phone_primary', sa.String(length=40), nullable=False),
    sa.Column('phone_secondary', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('governorate', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_medical_file_number'), ['medical_file_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_name_ar'), ['name_ar'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name_en'), ['name_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone_primary'), ['phone_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone_secondary'), ['phone_secondary'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_search_name'), ['search_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_uuid'))
        batch_op.drop_index(batch_op.f('ix_patients_search_name'))
        batch_op.drop_index(batch_op.f('ix_patients_phone_secondary'))
        batch_op.drop_index(batch_op.f('ix_patients_phone_primary'))
        batch_op.drop_index(batch_op.f('ix_patients_name_en'))
        batch_op.drop_index(batch_op.f('ix_patients_name_ar'))
        batch_op.drop_index(batch_op.f('ix_patients_medical_file_number'))

    op.drop_table('patients')
    # ### end Alembic commands ###
