"""add appointments

Revision ID: ecf98d78d1b4
Revises: 20260707_0005
Create Date: 2026-07-07 15:28:43.691044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf98d78d1b4'
down_revision = '20260707_0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('no_show_at', sa.DateTime(), nullable=True),
    sa.Column('rescheduled_at', sa.DateTime(), nullable=True),
    sa.Column('rescheduled_from_id', sa.Integer(), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_uuid'))
        batch_op.create_index(batch_op.f('ix_journeys_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_uuid'))
        batch_op.create_index(batch_op.f('ix_visits_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_uuid'))
        batch_op.create_index(batch_op.f('ix_visits_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journeys_uuid'))
        batch_op.create_index(batch_op.f('ix_journeys_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
