import uuid as uuid_lib
from datetime import date, datetime, timezone
from decimal import Decimal

from app.extensions import db


class FinanceCharge(db.Model):
    """Expected patient-related income generated by embedded clinic workflows."""

    __tablename__ = "finance_charges"

    STATUS_UNPAID = "unpaid"
    STATUS_PARTIAL = "partial"
    STATUS_PAID = "paid"
    STATUS_CANCELLED = "cancelled"

    VALID_STATUSES = {
        STATUS_UNPAID,
        STATUS_PARTIAL,
        STATUS_PAID,
        STATUS_CANCELLED,
    }

    SOURCE_APPOINTMENT = "appointment"
    SOURCE_VISIT = "visit"
    SOURCE_SURGERY = "surgery"
    SOURCE_MANUAL = "manual"

    SERVICE_CONSULTATION = "consultation"
    SERVICE_FOLLOW_UP = "follow_up"
    SERVICE_EMERGENCY = "emergency"
    SERVICE_SURGERY = "surgery"
    SERVICE_PROCEDURE = "procedure"
    SERVICE_ULTRASOUND = "ultrasound"
    SERVICE_INVESTIGATION = "investigation"
    SERVICE_OTHER = "other"

    VALID_SERVICE_TYPES = {
        SERVICE_CONSULTATION,
        SERVICE_FOLLOW_UP,
        SERVICE_EMERGENCY,
        SERVICE_SURGERY,
        SERVICE_PROCEDURE,
        SERVICE_ULTRASOUND,
        SERVICE_INVESTIGATION,
        SERVICE_OTHER,
    }

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(
        db.String(36),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid_lib.uuid4()),
    )

    patient_id = db.Column(db.Integer, db.ForeignKey("patients.id"), nullable=False, index=True)

    source_type = db.Column(db.String(40), nullable=False, index=True)
    source_id = db.Column(db.Integer, nullable=True, index=True)
    service_type = db.Column(db.String(40), nullable=False, index=True)

    title = db.Column(db.String(180), nullable=False)
    description = db.Column(db.Text, nullable=True)

    gross_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))
    discount_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))
    net_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))
    paid_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))
    remaining_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))

    status = db.Column(db.String(40), nullable=False, default=STATUS_UNPAID, index=True)
    service_date = db.Column(db.Date, nullable=False, default=date.today, index=True)

    created_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True, index=True)
    updated_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True, index=True)

    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    patient = db.relationship("Patient", backref=db.backref("finance_charges", lazy="dynamic"))
    created_by_user = db.relationship("User", foreign_keys=[created_by_user_id])
    updated_by_user = db.relationship("User", foreign_keys=[updated_by_user_id])

    __table_args__ = (
        db.Index("ix_finance_charges_source", "source_type", "source_id"),
        db.Index("ix_finance_charges_date_service", "service_date", "service_type"),
    )

    def __repr__(self):
        return f"<FinanceCharge {self.uuid} {self.source_type}:{self.source_id} {self.status}>"


class FinancePayment(db.Model):
    """Actual received money."""

    __tablename__ = "finance_payments"

    METHOD_CASH = "cash"
    METHOD_INSTAPAY = "instapay"
    METHOD_VODAFONE_CASH = "vodafone_cash"
    METHOD_CARD = "card"
    METHOD_BANK_TRANSFER = "bank_transfer"
    METHOD_OTHER = "other"

    VALID_METHODS = {
        METHOD_CASH,
        METHOD_INSTAPAY,
        METHOD_VODAFONE_CASH,
        METHOD_CARD,
        METHOD_BANK_TRANSFER,
        METHOD_OTHER,
    }

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(
        db.String(36),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid_lib.uuid4()),
    )

    patient_id = db.Column(db.Integer, db.ForeignKey("patients.id"), nullable=False, index=True)
    charge_id = db.Column(db.Integer, db.ForeignKey("finance_charges.id"), nullable=True, index=True)

    payment_date = db.Column(db.Date, nullable=False, default=date.today, index=True)
    amount = db.Column(db.Numeric(12, 2), nullable=False)
    payment_method = db.Column(db.String(40), nullable=False, index=True)

    notes = db.Column(db.Text, nullable=True)

    created_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True, index=True)
    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    patient = db.relationship("Patient", backref=db.backref("finance_payments", lazy="dynamic"))
    charge = db.relationship("FinanceCharge", backref=db.backref("payments", lazy="dynamic", cascade="all, delete-orphan"))
    created_by_user = db.relationship("User", foreign_keys=[created_by_user_id])

    def __repr__(self):
        return f"<FinancePayment {self.uuid} amount={self.amount} method={self.payment_method}>"


class FinanceExpense(db.Model):
    """Clinic-level expense not linked to a patient."""

    __tablename__ = "finance_expenses"

    CATEGORY_CONSUMABLES = "consumables"
    CATEGORY_SALARIES = "salaries"
    CATEGORY_RENT = "rent"
    CATEGORY_UTILITIES = "utilities"
    CATEGORY_MAINTENANCE = "maintenance"
    CATEGORY_EQUIPMENT = "equipment"
    CATEGORY_MARKETING = "marketing"
    CATEGORY_CLEANING = "cleaning"
    CATEGORY_OTHER = "other"

    VALID_CATEGORIES = {
        CATEGORY_CONSUMABLES,
        CATEGORY_SALARIES,
        CATEGORY_RENT,
        CATEGORY_UTILITIES,
        CATEGORY_MAINTENANCE,
        CATEGORY_EQUIPMENT,
        CATEGORY_MARKETING,
        CATEGORY_CLEANING,
        CATEGORY_OTHER,
    }

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(
        db.String(36),
        unique=True,
        nullable=False,
        index=True,
        default=lambda: str(uuid_lib.uuid4()),
    )

    expense_date = db.Column(db.Date, nullable=False, default=date.today, index=True)
    category = db.Column(db.String(40), nullable=False, index=True)
    title = db.Column(db.String(180), nullable=False)
    amount = db.Column(db.Numeric(12, 2), nullable=False)
    payment_method = db.Column(db.String(40), nullable=False, index=True)
    vendor_or_staff_name = db.Column(db.String(180), nullable=True)
    notes = db.Column(db.Text, nullable=True)

    created_by_user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True, index=True)

    created_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    created_by_user = db.relationship("User", foreign_keys=[created_by_user_id])

    def __repr__(self):
        return f"<FinanceExpense {self.uuid} {self.category} amount={self.amount}>"
